config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#index'
  get 'likes/create'
  get 'top/main'
  get 'top/logout'
  post 'likes/create'
  delete 'likes/destroy/', to: 'likes#destroy'
  resources :top
  resources :users
  resources :tweets
  post 'top/login'
  get 'top/logout'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :tweet, optional: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes,dependent: :destroy
    has_many :like_users, through: :likes, source: :user, dependent: :destroy
    
    def like(user)
        likes.create(user_id: user.id)
    end
    
    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
    
    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets,dependent: :destroy
    has_many :likes,dependent: :destroy
    has_many :like_tweets, through: :likes, source: :tweet,dependent: :destroy
    
    validates :password, presence: true, confirmation: true
    attr_accessor :password, :password_confirmation
    
    def password=(val)
    if val.present?
        self.pass = BCrypt::Password.create(val)
    end
    @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    private
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
    helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
      tweet.like(current_user)
    end
    redirect_to root_path
  end
  
  def destroy
    tweet = Tweet.find(params[:tweet_id])
    if tweet.liked?(current_user)
      tweet.unlike(current_user)
    end
    redirect_to root_path
    
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render'login_form'
  end

  def login
    if user = User.find_by(uid: params[:uid])
      
      if BCrypt::Password.new(user.pass) == params[:pass]
        session[:login_uid] = params[:uid]
        redirect_to root_path
      else
        render 'login_form' 
      end
      
    else
      render 'login_form'
      
    end
  end

  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.all
    @like = Like.all
    @user = User.find_by(uid: session[:login_uid])
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    user = User.find_by(uid: current_user.uid)
    @tweet = Tweet.create(message: params[:tweet][:message])
    user.tweets << @tweet
    @tweet.user = user
    if @tweet.save
      redirect_to '/'
    else
        render 'new'
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user=User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
    uid: params[:user][:uid],
    password: params[:user][:password],
    password_confirmation: params[:user][:password_confirmation])
    if @user.save
      redirect_to users_path
    else
    render 'new'
end
    
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to '/users'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    
    <p>
      <% if session[:login_uid] %>
    <p><%= p "ログイン中です（#{current_user.uid}さん）"%></p>
      <% else %>
        <p>ログインしていません</p>
      <% end %>
      </p>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/top/login_form.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>
<p><%= link_to 'ユーザ一覧',users_path%></p>

app/views/top/main.html.erb
<%= form_tag '/top/login', method: :post do %>
<%= label_tag :uid, 'ユーザーID' %>
<%= text_field_tag :uid %>
<%= label_tag :pass, 'パスワード' %>
<%= password_field_tag :pass %>
<%= submit_tag '登録' %>
<% end %>
<%= link_to 'ユーザ一覧','/users/index' %>

<% if session[:login_uid] %>
    <p><%= p "ログイン中です（#{session[:login_uid]}さん）"%></p>
<% else %>
    <p>ログインしていません</p>
<% end %>

app/views/tweets/index.html.erb
<% @tweet.each do |e| %>
    <%= e.message %>
    <% if session[:login_uid] %>
        <%= link_to 'いいね', likes_create_path(tweet_id: e.id), method: :post %>
        <%= link_to 'いいね削除', likes_destroy_path(tweet_id: e.id), method: :delete %>
        <% if @like.find_by(tweet_id: e.id,user_id: @user.id) %>
            <%= p '🤍' %>
        <% else %>
            <%= p '♡' %>
        <%end%>
        <%= link_to '削除',"/tweets/#{e.id}",method: :delete %>
    <%end%>
    
    
    <br>
<% end %>


<% if session[:login_uid] %>
    <p><%= link_to 'ツイート','/tweets/new'%></p>
    <p><%= link_to 'ログアウト',top_logout_path %></p>
<% else %>
    <%= link_to 'ログイン','/top/main' %>
<% end %>

app/views/tweets/new.html.erb
<%= form_for @tweet , url: {action: :create} do |f| %>
<%= f.text_area :message,size:"30x10" %>
<%= f.submit 'ツイート'  %>
<% end %>

app/views/users/index.html.erb
<% @user.each do |user| %>
    <%= 'ユーザID:' %>
        <%= user.uid %>
    <%= '年齢:'%>
        <%= user.age%>
    <%= 'パスワード:'%>
        <%= user.pass%>
    <%= link_to '削除',"/users/#{user.id}",method: :delete %><br>
<% end %>

<p><%= link_to 'ユーザ作成','/users/new'%></p>
<p><%= link_to 'メイン','/' %></p>

app/views/users/new.html.erb
<%= form_for @user, url:{action: :create} do |f| %>
    <%= 'ユーザID：' %>
        <%= f.text_field :uid %><br>
    <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password %>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation %>
    <%= '年齢：' %>
        <%= f.number_field :age %><br>
    <%= f.submit '登録' %>
    
<% end %>